const questionsData = [
    // --- VERDADERO / FALSO (1-37) ---
    { id: "TF-1", type: "TF", topic: "Yijing", q: "The double-fish logo of Yijing signifies unity of opposites, mutual complementation, mutual transformation, non-duality, etc.", a: "True", doc: "Yijing", pg: "1" },
    { id: "TF-2", type: "TF", topic: "Yijing", q: "The origin of traditional Chinese philosophy is Yijing, which is later inherited by both Taoism and Confucianism.", a: "True", doc: "Yijing", pg: "2" },
    { id: "TF-3", type: "TF", topic: "Yijing", q: "The Double-Ninth Festival... stands for the highest state of Yin.", a: "False", doc: "Yijing", pg: "3" },
    { id: "TF-4", type: "TF", topic: "Yijing", q: "Traditional Chinese medical science is NOT related to the Yin-Yang theory.", a: "False", doc: "Yijing", pg: "4" },
    { id: "TF-5", type: "TF", topic: "Taoism", q: "The famous quote 'The journey of a thousand miles began with what was under the feet' comes from Daodejing.", a: "True", doc: "Taoism", pg: "5" },
    { id: "TF-6", type: "TF", topic: "Taoism", q: "Naturalness is a trademark value of Taoism.", a: "True", doc: "Taoism", pg: "6" },
    { id: "TF-7", type: "TF", topic: "Taoism", q: "The mind as a mirror is a metaphor embraced by Taoism only.", a: "False", doc: "Taoism", pg: "7" },
    { id: "TF-8", type: "TF", topic: "Taoism", q: "Zhuangzi's response at the death of his wife contradicts the story of the fish partners.", a: "False", doc: "Taoism", pg: "8" },
    { id: "TF-9", type: "TF", topic: "Taoism", q: "One branch of religious Taoism has practitioners who remain single, eat no meat and drink no alcohol.", a: "True", doc: "Taoism", pg: "9" },
    { id: "TF-10", type: "TF", topic: "Taoism", q: "One branch of religious Taoism has adopted the Buddhist heart sutra.", a: "True", doc: "Taoism", pg: "10" },
    { id: "TF-11", type: "TF", topic: "Taoism", q: "China's lunar rover Rabbit is so called because it moves about like a rabbit.", a: "False", doc: "Folklore", pg: "11" },
    { id: "TF-12", type: "TF", topic: "Confucianism", q: "Confucius was a contemporary of Laozi and was about 20 years his junior.", a: "True", doc: "Confucianism", pg: "12" },
    { id: "TF-13", type: "TF", topic: "Confucianism", q: "Confucius praised his disciple Zi Gong, who rejected rewards for freeing captives.", a: "False", doc: "Confucianism", pg: "13" },
    { id: "TF-14", type: "TF", topic: "Confucianism", q: "Mencius was a contemporary of Zhuangzi.", a: "True", doc: "Confucianism", pg: "14" },
    { id: "TF-15", type: "TF", topic: "Confucianism", q: "Confucianism is supportive of mercantilism.", a: "False", doc: "Confucianism", pg: "15" },
    { id: "TF-16", type: "TF", topic: "Confucianism", q: "Confucius held a hearing in which a father charged his son with filial impiety.", a: "False", doc: "Confucianism", pg: "16" },
    { id: "TF-17", type: "TF", topic: "Legalism", q: "Mozi was the founder of Mohism and was not a Legalist nor Logician.", a: "False", doc: "Legalism", pg: "17" },
    { id: "TF-18", type: "TF", topic: "Legalism", q: "Rites and righteousness are upheld by Confucians only and not by Legalists.", a: "False", doc: "Legalism", pg: "18" },
    { id: "TF-19", type: "TF", topic: "Legalism", q: "Fa also means administrative methods and standards, not just law.", a: "True", doc: "Legalism", pg: "19" },
    { id: "TF-20", type: "TF", topic: "Mohism", q: "Mozi was a military expert but called for peace.", a: "True", doc: "Mohism", pg: "20" },
    { id: "TF-21", type: "TF", topic: "Mohism", q: "Mozi was not good at the study of logic.", a: "False", doc: "Mohism", pg: "21" },
    { id: "TF-22", type: "TF", topic: "Mohism", q: "Mozi was in favor of patterning modern life on ancient sages.", a: "False", doc: "Mohism", pg: "22" },
    { id: "TF-23", type: "TF", topic: "Mohism", q: "Mozi did not emphasize introspection and authenticity.", a: "False", doc: "Mohism", pg: "23" },
    { id: "TF-24", type: "TF", topic: "Nominalism", q: "The arrow flies fast... comes from the book Zhuangzi.", a: "True", doc: "Nominalism", pg: "24" },
    { id: "TF-25", type: "TF", topic: "Nominalism", q: "Hui Shi was wrong in assuming the center of the world can be north of Yan.", a: "False", doc: "Nominalism", pg: "25" },
    { id: "TF-26", type: "TF", topic: "Nominalism", q: "Nominalism in Chinese is called Mingjia.", a: "True", doc: "Nominalism", pg: "26" },
    { id: "TF-27", type: "TF", topic: "Strategy", q: "Sunzi was a contemporary of Confucius.", a: "True", doc: "Strategy", pg: "27" },
    { id: "TF-28", type: "TF", topic: "Strategy", q: "Sunzi lived in the Warring States period.", a: "False", doc: "Strategy", pg: "28" },
    { id: "TF-29", type: "TF", topic: "Strategy", q: "The Art of War is only applied to military affairs today.", a: "False", doc: "Strategy", pg: "29" },
    { id: "TF-30", type: "TF", topic: "Buddhism", q: "Enlightenment in Buddhism cannot be fully expressed by language.", a: "True", doc: "Buddhism", pg: "30" },
    { id: "TF-31", type: "TF", topic: "Buddhism", q: "In Zen, the mind is compared to a mirror as well.", a: "True", doc: "Buddhism", pg: "31" },
    { id: "TF-32", type: "TF", topic: "Buddhism", q: "All Buddhist monks in China are vegetarians.", a: "False", doc: "Buddhism", pg: "32" },
    { id: "TF-33", type: "TF", topic: "Buddhism", q: "Buddhism believes everyone can be a Buddha.", a: "True", doc: "Buddhism", pg: "33" },
    { id: "TF-34", type: "TF", topic: "Buddhism", q: "Amitabha is so popular that his name is used for greetings.", a: "True", doc: "Buddhism", pg: "34" },
    { id: "TF-35", type: "TF", topic: "Neo-Confucianism", q: "Lu Jiuyuan was not a contemporary of Zhu Xi.", a: "False", doc: "NeoConf", pg: "35" },
    { id: "TF-36", type: "TF", topic: "Neo-Confucianism", q: "Zhu Xi made an analogy between the mind and the mirror.", a: "True", doc: "NeoConf", pg: "36" },
    { id: "TF-37", type: "TF", topic: "Neo-Confucianism", q: "Neo-Confucians warmly embrace Buddhism/Taoism and become strict practitioners.", a: "False", doc: "NeoConf", pg: "37" },

    // --- OPCIÓN MÚLTIPLE (MC 1-113) ---
    // Yijing (1-15)
    { id: "MC-1", type: "MC", topic: "Yijing", q: "What is the Book of Changes called in Chinese?", o: ["Xin Jing", "Yi Jing", "Dao De Jing"], a: "Yi Jing" },
    { id: "MC-2", type: "MC", topic: "Yijing", q: "How to say the eight trigrams in Chinese?", o: ["ba gua", "yin yang", "tai ji"], a: "ba gua" },
    { id: "MC-3", type: "MC", topic: "Yijing", q: "Famous commentator of the Book of Changes?", o: ["Zhou Wenwang", "Fu Xi", "Kong Zi"], a: "Kong Zi" },
    { id: "MC-4", type: "MC", topic: "Yijing", q: "The Positive (Yang) can be represented by:", o: ["—", "•", "- -"], a: "—" },
    { id: "MC-5", type: "MC", topic: "Yijing", q: "Blocks like ☰, ☱ are called:", o: ["hexagrams", "trigrams", "hologram"], a: "trigrams" },
    { id: "MC-6", type: "MC", topic: "Yijing", q: "The singularity point is NOT related to:", o: ["big bang", "black hole", "telepathy"], a: "telepathy" },
    { id: "MC-7", type: "MC", topic: "Yijing", q: "'Spooky action at a distance' is from:", o: ["Einstein", "Bohr", "Laozi"], a: "Einstein" },
    { id: "MC-8", type: "MC", topic: "Yijing", q: "Bohr's coat of arms motto:", o: ["I think...", "Opposites are complementary", "Go have tea"], a: "Opposites are complementary" },
    { id: "MC-9", type: "MC", topic: "Yijing", q: "Quantum entanglement similarity EXCEPT:", o: ["non-duality", "opposite directions", "constant transformation"], a: "constant transformation" },
    { id: "MC-10", type: "MC", topic: "Yijing", q: "Concept of singularity point is similar to:", o: ["tai ji", "wu ji", "ba gua"], a: "tai ji" },
    { id: "MC-11", type: "MC", topic: "Yijing", q: "Concept of black hole/voidness is similar to:", o: ["liang yi", "wu ji", "tai ji"], a: "wu ji" },
    { id: "MC-12", type: "MC", topic: "Yijing", q: "Logo of double-fish with eight trigrams:", o: ["tai ji tu", "ba gua tu", "tai ji ba gua tu"], a: "tai ji ba gua tu" },
    { id: "MC-13", type: "MC", topic: "Yijing", q: "Theory that 3D world is a projection of 2D:", o: ["hologram hypothesis", "butterfly dream", "manifested body"], a: "hologram hypothesis" },
    { id: "MC-14", type: "MC", topic: "Yijing", q: "In computers (0 and 1), these numbers are NOT called:", o: ["yin yang", "wu ji", "liang yi"], a: "wu ji" },
    { id: "MC-15", type: "MC", topic: "Yijing", q: "Looking at potential opportunities behind crisis is:", o: ["sophistry", "ontology", "dialectics"], a: "dialectics" },

    // Taoism (16-37)
    { id: "MC-16", type: "MC", topic: "Taoism", q: "Founder of philosophical Taoism:", o: ["Laozi", "Zhuangzi", "Mencius"], a: "Laozi" },
    { id: "MC-17", type: "MC", topic: "Taoism", q: "Chinese for 'The Way and Virtue':", o: ["Xin Jing", "Dao De Jing", "Jin Gang Jing"], a: "Dao De Jing" },
    { id: "MC-18", type: "MC", topic: "Taoism", q: "Taoist concept of inaction:", o: ["zi ran", "wu zheng", "wu wei"], a: "wu wei" },
    { id: "MC-19", type: "MC", topic: "Taoism", q: "Historical period of Laozi:", o: ["Spring and Autumn", "Warring States", "Song dynasty"], a: "Spring and Autumn" },
    { id: "MC-20", type: "MC", topic: "Taoism", q: "Author of Daodejing lived how many years ago?", o: ["2300", "2500", "2000"], a: "2500" },
    { id: "MC-21", type: "MC", topic: "Taoism", q: "Story of old man who lost his horse tells us:", o: ["law is pivotal", "white horses...", "pos/neg go hand in hand"], a: "pos/neg go hand in hand" },
    { id: "MC-22", type: "MC", topic: "Taoism", q: "Idiom for Laozi showing his tongue but no teeth:", o: ["shang shan ruo shui", "zhi zu chang le", "huo fu xiang yi"], a: "shang shan ruo shui" },
    { id: "MC-23", type: "MC", topic: "Taoism", q: "Which is NOT a Taoist resort?", o: ["Qing Cheng Shan", "E Mei Shan", "Qing Yang Gong"], a: "E Mei Shan" },
    { id: "MC-24", type: "MC", topic: "Taoism", q: "Second most important Taoist master:", o: ["Gongsun Long", "Mo Zi", "Zhuangzi"], a: "Zhuangzi" },
    { id: "MC-25", type: "MC", topic: "Taoism", q: "Collection of works by Zhuangzi:", o: ["Zhuangzi", "Da Xue", "Zhong Yong"], a: "Zhuangzi" },
    { id: "MC-26", type: "MC", topic: "Taoism", q: "Zhuangzi is NOT famous for:", o: ["detachment", "applying art of war", "allegorical stories"], a: "applying art of war" },
    { id: "MC-27", type: "MC", topic: "Taoism", q: "Zhuangzi's butterfly dream is NOT related to:", o: ["relativity", "transformation", "sweet innocence"], a: "sweet innocence" },
    { id: "MC-28", type: "MC", topic: "Taoism", q: "Story of happiness of fish is related to:", o: ["insight into logic", "detachment", "unity with nature"], a: "insight into logic" },
    { id: "MC-29", type: "MC", topic: "Taoism", q: "Perfect Man uses mind like a mirror is NOT related to:", o: ["naturalness", "frugality", "inaction"], a: "frugality" },
    { id: "MC-30", type: "MC", topic: "Taoism", q: "Fighting at snail's antennas indicates:", o: ["loyalty", "law", "men are short-sighted"], a: "men are short-sighted" },
    { id: "MC-31", type: "MC", topic: "Taoism", q: "Fish partners in drying lake tells us to:", o: ["detach from bondage", "help each other", "protect eco-system"], a: "detach from bondage" },
    { id: "MC-32", type: "MC", topic: "Taoism", q: "In religious Taoism, ruler in heaven:", o: ["Yu Tu", "Yu Di", "Lao Zi"], a: "Yu Di" },
    { id: "MC-33", type: "MC", topic: "Taoism", q: "Religious Taoism main branches NOT including:", o: ["Zheng Yi", "Quan Zhen", "Da Cheng Jiao"], a: "Da Cheng Jiao" },
    { id: "MC-34", type: "MC", topic: "Taoism", q: "Early Taoist alchemists invented by chance:", o: ["gunpowder", "compass", "paper"], a: "gunpowder" },
    { id: "MC-35", type: "MC", topic: "Taoism", q: "Lady who flies to moon with rabbit:", o: ["Nu Wa", "Chang'e", "Fu Hao"], a: "Chang'e" },
    { id: "MC-36", type: "MC", topic: "Taoism", q: "Deity symbol of longevity:", o: ["Fu Xing", "Lu Xing", "Shou Xing"], a: "Shou Xing" },
    { id: "MC-37", type: "MC", topic: "Taoism", q: "Pictures of door guardians:", o: ["Men Shen", "Tu Di Gong", "Zao Shen"], a: "Men Shen" },

    // Confucianism (38-52)
    { id: "MC-38", type: "MC", topic: "Confucianism", q: "Schools of thought contending:", o: ["si shu wu jing", "bai jia zheng ming", "bai ma fei ma"], a: "bai jia zheng ming" },
    { id: "MC-39", type: "MC", topic: "Confucianism", q: "Confucianism established by:", o: ["Meng Zi", "Xun Zi", "Kong Zi"], a: "Kong Zi" },
    { id: "MC-40", type: "MC", topic: "Confucianism", q: "Second most important Confucian master:", o: ["Meng Zi", "Xun Zi", "Kong Zi"], a: "Meng Zi" },
    { id: "MC-41", type: "MC", topic: "Confucianism", q: "Confucianism in Chinese:", o: ["Dao Jia", "Ru Jia", "Ming Jia"], a: "Ru Jia" },
    { id: "MC-42", type: "MC", topic: "Confucianism", q: "Confucius was NOT fond of:", o: ["governance", "education", "non-competition"], a: "non-competition" },
    { id: "MC-43", type: "MC", topic: "Confucianism", q: "Core value of Confucianism:", o: ["ren", "yi", "li"], a: "ren" },
    { id: "MC-44", type: "MC", topic: "Confucianism", q: "Filial piety in Chinese:", o: ["zhong", "xiao", "jie"], a: "xiao" },
    { id: "MC-45", type: "MC", topic: "Confucianism", q: "Book of Rites is called:", o: ["Shang Shu", "Shi Jing", "Zhou Li"], a: "Zhou Li" },
    { id: "MC-46", type: "MC", topic: "Confucianism", q: "Words and deeds of Confucius recorded in:", o: ["Lun Yu", "Tan Jing", "Chun Qiu"], a: "Lun Yu" },
    { id: "MC-47", type: "MC", topic: "Confucianism", q: "Confucian value 'Ren' means:", o: ["righteousness", "humanity", "loyalty"], a: "humanity" },
    { id: "MC-48", type: "MC", topic: "Confucianism", q: "Mencius' mother moved how many times?", o: ["once", "2 times", "3 times"], a: "3 times" },
    { id: "MC-49", type: "MC", topic: "Confucianism", q: "Cutting cloth on loom means:", o: ["giving up study is loss", "poor quality", "make a coat"], a: "giving up study is loss" },
    { id: "MC-50", type: "MC", topic: "Confucianism", q: "Mencius view:", o: ["nature is evil", "common people most valuable", "ruler significant"], a: "common people most valuable" },
    { id: "MC-51", type: "MC", topic: "Confucianism", q: "'Believing in everything in books is worse...':", o: ["Mozi", "Confucius", "Mencius"], a: "Mencius" },
    { id: "MC-52", type: "MC", topic: "Confucianism", q: "Superior man (gentleman):", o: ["jun zi", "sheng ren", "yi shi"], a: "jun zi" },

    // Legalism (53-67)
    { id: "MC-53", type: "MC", topic: "Legalism", q: "Legalism branch called:", o: ["Bing Jia", "Fa Jia", "Fo Jia"], a: "Fa Jia" },
    { id: "MC-54", type: "MC", topic: "Legalism", q: "Fa derived from:", o: ["Shi Jing", "Shang Shu", "Zhou Li"], a: "Zhou Li" },
    { id: "MC-55", type: "MC", topic: "Legalism", q: "Legalist in Spring/Autumn period:", o: ["Guan Zhong", "Shang Yang", "Han Fei Zi"], a: "Guan Zhong" },
    { id: "MC-56", type: "MC", topic: "Legalism", q: "'When granary is full... people learn etiquette':", o: ["Taoism", "Legalism", "Confucianism"], a: "Legalism" },
    { id: "MC-57", type: "MC", topic: "Legalism", q: "Four dimensions (Rites, Righteousness...):", o: ["Confucianism", "Taoism", "Legalism"], a: "Legalism" },
    { id: "MC-58", type: "MC", topic: "Legalism", q: "What does 'Model' mean here?", o: ["Fa", "Dao", "Ren"], a: "Fa" },
    { id: "MC-59", type: "MC", topic: "Legalism", q: "Who rewarded people for moving a log?", o: ["Mo Zi", "Shang Yang", "Hui Shi"], a: "Shang Yang" },
    { id: "MC-60", type: "MC", topic: "Legalism", q: "First emperor (Qin):", o: ["Tang Tai Zong", "Han Wu Di", "Qin Shi Huang"], a: "Qin Shi Huang" },
    { id: "MC-61", type: "MC", topic: "Legalism", q: "Greatest Legalist text (240 BC):", o: ["Han Feizi", "Guanzi", "Mengzi"], a: "Han Feizi" },
    { id: "MC-62", type: "MC", topic: "Legalism", q: "Prince must surround himself with:", o: ["affinity", "majesty and power", "benevolence"], a: "majesty and power" },
    { id: "MC-63", type: "MC", topic: "Legalism", q: "Story of spear and shield:", o: ["Mozi", "Lunyu", "Han Feizi"], a: "Han Feizi" },
    { id: "MC-64", type: "MC", topic: "Legalism", q: "Grant authority to 'wise ministers':", o: ["Confucianism", "Legalism", "Nominalism"], a: "Confucianism" },
    { id: "MC-65", type: "MC", topic: "Legalism", q: "Selfish view of human nature:", o: ["Taoists", "Legalists", "Confucians"], a: "Legalists" },
    { id: "MC-66", type: "MC", topic: "Legalism", q: "Replace aristocracy with:", o: ["authority", "benevolence", "bureaucracy"], a: "bureaucracy" },
    { id: "MC-67", type: "MC", topic: "Legalism", q: "Legalists do NOT advocate:", o: ["charisma of officials", "central government", "food production"], a: "charisma of officials" },

    // Mohism (68-75)
    { id: "MC-68", type: "MC", topic: "Mohism", q: "Quantum satellite named:", o: ["Pan Jianwei", "Mozi", "Han Feizi"], a: "Mozi" },
    { id: "MC-69", type: "MC", topic: "Mohism", q: "NOT natives of Shandong:", o: ["Confucius/Mencius", "Sunzi/Mozi", "Laozi/Zhuangzi"], a: "Laozi/Zhuangzi" },
    { id: "MC-70", type: "MC", topic: "Mohism", q: "Viewed funerals as detrimental:", o: ["Mo Zi", "Sun Zi", "Meng Zi"], a: "Mo Zi" },
    { id: "MC-71", type: "MC", topic: "Mohism", q: "Everyone equal in eyes of heaven:", o: ["Meng Zi", "Mo Zi", "Sun Zi"], a: "Mo Zi" },
    { id: "MC-72", type: "MC", topic: "Mohism", q: "Universal love in Chinese:", o: ["jie yong", "fei gong", "jian ai"], a: "jian ai" },
    { id: "MC-73", type: "MC", topic: "Mohism", q: "Mozi sad at dyeing silk because:", o: ["costly", "better looking", "reminded of sad past"], a: "reminded of sad past" },
    { id: "MC-74", type: "MC", topic: "Mohism", q: "Peach for a plum means:", o: ["tooth for tooth", "favor for favor", "mismatch"], a: "favor for favor" },
    { id: "MC-75", type: "MC", topic: "Mohism", q: "NOT a contribution by Mozi:", o: ["lever principle", "light in straight line", "general relativity"], a: "general relativity" },

    // Nominalism (76-85)
    { id: "MC-76", type: "MC", topic: "Nominalism", q: "Nominalists are NOT called:", o: ["Rationalists", "Logicians", "Disputers"], a: "Rationalists" },
    { id: "MC-77", type: "MC", topic: "Nominalism", q: "Nominalism grew out of:", o: ["Neo-Confucianism", "Mohism", "Book of Rites"], a: "Mohism" },
    { id: "MC-78", type: "MC", topic: "Nominalism", q: "Hui Shi and Gongsun Long lived in:", o: ["Western Zhou", "Spring/Autumn", "Warring States"], a: "Warring States" },
    { id: "MC-79", type: "MC", topic: "Nominalism", q: "Knowledge of Hui Shi relies on:", o: ["Zhuangzi", "Han Feizi", "Lüshi Chunqiu"], a: "Zhuangzi" },
    { id: "MC-80", type: "MC", topic: "Nominalism", q: "'Set off today and came yesterday':", o: ["absurdity", "relativity of time/space", "devotion"], a: "relativity of time/space" },
    { id: "MC-81", type: "MC", topic: "Nominalism", q: "Hui Shi proponent of:", o: ["mind as mirror", "hardness/whiteness", "sameness/difference"], a: "sameness/difference" },
    { id: "MC-82", type: "MC", topic: "Nominalism", q: "Heaven low as earth is an attempt to:", o: ["harmonize sameness/difference", "compare mind to mirror", "divide hardness"], a: "harmonize sameness/difference" },
    { id: "MC-83", type: "MC", topic: "Nominalism", q: "Happiness of fish debate:", o: ["Gongsun Long", "Hui Shi", "Yin Wen"], a: "Hui Shi" },
    { id: "MC-84", type: "MC", topic: "Nominalism", q: "NOT attributed to Gongsun Long:", o: ["White horses", "Hardness/whiteness", "Linked rings can be separated"], a: "Linked rings can be separated" },
    { id: "MC-85", type: "MC", topic: "Nominalism", q: "NOT a Greek paradox:", o: ["Shadow of flying bird", "Tortoise", "Flying arrow static"], a: "Shadow of flying bird" },

    // Strategy (86-89)
    { id: "MC-86", type: "MC", topic: "Strategy", q: "Art of War written by:", o: ["Mozi", "Sunzi", "Zhu Xi"], a: "Sunzi" },
    { id: "MC-87", type: "MC", topic: "Strategy", q: "NOT a contemporary of Sunzi:", o: ["Laozi", "Confucius", "Gongsun Long"], a: "Gongsun Long" },
    { id: "MC-88", type: "MC", topic: "Strategy", q: "Highest art of war:", o: ["rivalry of strategies", "diplomatic", "direct fight"], a: "rivalry of strategies" },
    { id: "MC-89", type: "MC", topic: "Strategy", q: "Know enemy and yourself:", o: ["bu zhan er qu", "zhi bi zhi ji", "shang bing fa mou"], a: "zhi bi zhi ji" },

    // Buddhism (90-101)
    { id: "MC-90", type: "MC", topic: "Buddhism", q: "NOT a Buddhist mountain:", o: ["E Mei Shan", "Le Shan", "Qing Cheng Shan"], a: "Qing Cheng Shan" },
    { id: "MC-91", type: "MC", topic: "Buddhism", q: "Founded on our thoughts:", o: ["Fo Jiao", "Dao Jiao", "Ru Jiao"], a: "Fo Jiao" },
    { id: "MC-92", type: "MC", topic: "Buddhism", q: "Highest heaven/realm:", o: ["physical forms", "formless realm", "desire"], a: "formless realm" },
    { id: "MC-93", type: "MC", topic: "Buddhism", q: "Shortest scripture (260 chars):", o: ["Platform Sutra", "Diamond Sutra", "Heart Sutra"], a: "Heart Sutra" },
    { id: "MC-94", type: "MC", topic: "Buddhism", q: "Dharma body means:", o: ["formless/all-pervasive", "manifested", "reincarnated"], a: "formless/all-pervasive" },
    { id: "MC-95", type: "MC", topic: "Buddhism", q: "NOT a feature of Zen:", o: ["Hit with stick", "Recite Amitabha", "Have tea"], a: "Recite Amitabha" },
    { id: "MC-96", type: "MC", topic: "Buddhism", q: "Han and Tibetan tradition called:", o: ["Hinayana", "Theravada", "Mahayana"], a: "Mahayana" },
    { id: "MC-97", type: "MC", topic: "Buddhism", q: "Theravada practiced in:", o: ["Yunnan", "Inner Mongolia", "Guangxi"], a: "Yunnan" },
    { id: "MC-98", type: "MC", topic: "Buddhism", q: "NOT a Han Buddhism sect:", o: ["Zen", "Dharma-Image", "Pure Land"], a: "Dharma-Image" },
    { id: "MC-99", type: "MC", topic: "Buddhism", q: "Latest sect in Tibetan Buddhism:", o: ["Red", "White", "Yellow"], a: "Yellow" },
    { id: "MC-100", type: "MC", topic: "Buddhism", q: "Form does not differ from emptiness:", o: ["Heart Sutra", "Diamond Sutra", "Platform Sutra"], a: "Heart Sutra" },
    { id: "MC-101", type: "MC", topic: "Buddhism", q: "Goddess of Mercy name:", o: ["Wen Shu", "Guan Yin", "Shi Jia"], a: "Guan Yin" },

    // Neo-Confucianism (102-113)
    { id: "MC-102", type: "MC", topic: "Neo-Confucianism", q: "Neo-Confucianism EXCEPT:", o: ["Song", "Ming", "Tang"], a: "Tang" },
    { id: "MC-103", type: "MC", topic: "Neo-Confucianism", q: "NOT a main branch:", o: ["Esoteric", "Rationalism", "Mind school"], a: "Esoteric" },
    { id: "MC-104", type: "MC", topic: "Neo-Confucianism", q: "Birth of Neo-Confucianism (years ago):", o: ["1500", "1000", "2000"], a: "1000" },
    { id: "MC-105", type: "MC", topic: "Neo-Confucianism", q: "Master of masters:", o: ["Zhu Xi", "Cheng Hao", "Zhou Dunyi"], a: "Zhou Dunyi" },
    { id: "MC-106", type: "MC", topic: "Neo-Confucianism", q: "Influential master for 600 years:", o: ["Zhu Xi", "Cheng Yi", "Cheng Hao"], a: "Zhu Xi" },
    { id: "MC-107", type: "MC", topic: "Neo-Confucianism", q: "NOT favored by Neo-Confucianism:", o: ["Taoism", "Legalism", "Buddhism"], a: "Legalism" },
    { id: "MC-108", type: "MC", topic: "Neo-Confucianism", q: "Highest objective (best morality):", o: ["Zhen Ren", "Xian Ren", "Sheng Ren"], a: "Sheng Ren" },
    { id: "MC-109", type: "MC", topic: "Neo-Confucianism", q: "Everyone has perfect ____:", o: ["Li (Principle)", "Li (Rites)", "Ren"], a: "Li (Principle)" },
    { id: "MC-110", type: "MC", topic: "Neo-Confucianism", q: "NOT originated from Neo-Confucianism:", o: ["Zhi Xing He Yi", "Se Ji Shi Kong", "Li Zai Qi Xian"], a: "Se Ji Shi Kong" },
    { id: "MC-111", type: "MC", topic: "Neo-Confucianism", q: "Universe is my mind:", o: ["Gongsun Long", "Wang Yangming", "Lu Jiuyuan"], a: "Lu Jiuyuan" },
    { id: "MC-112", type: "MC", topic: "Neo-Confucianism", q: "I think, therefore flower exists:", o: ["Wang Yangming", "Cheng Hao", "Zhu Xi"], a: "Wang Yangming" },
    { id: "MC-113", type: "MC", topic: "Neo-Confucianism", q: "NOT related to Wang Yangming:", o: ["Four-Line Axiom", "Bodhi poem", "Longchang Awakening"], a: "Bodhi poem" }
];