const questionsData = [
    // --- TRUE / FALSE QUESTIONS (37 total) ---
    { id: "TF-1", type: "TF", topic: "Yijing", q: "The double-fish logo of Yijing signifies unity of opposites, mutual complementation, mutual transformation, non-duality, etc.", a: "True", doc: "Yijing_Summary.pdf", pg: "85" },
    { id: "TF-2", type: "TF", topic: "Yijing", q: "The origin of traditional Chinese philosophy is Yijing, which is later inherited by both Taoism and Confucianism.", a: "True", doc: "Yijing_Intro.pdf", pg: "14" },
    { id: "TF-3", type: "TF", topic: "Yijing", q: "The Double-Ninth Festival, falling on the ninth day of the ninth lunar month, is designated as a day to show respect to the elders because the number nine stands for the highest state of Yin.", a: "False", doc: "Yijing_Practical.pdf", pg: "62" },
    { id: "TF-4", type: "TF", topic: "Yijing", q: "Traditional Chinese medical science is NOT related to the Yin-Yang theory.", a: "False", doc: "Yijing_TCM.pdf", pg: "75" },
    { id: "TF-5", type: "TF", topic: "Taoism", q: "The famous quote 'qiān lǐ zhī xíng, shǐ yú zú xià', or 'The journey of a thousand miles began with what was under the feet', comes from Daodejing.", a: "True", doc: "Laozi_Daodejing.pdf", pg: "39" },
    { id: "TF-6", type: "TF", topic: "Taoism", q: "Naturalness is a trademark value of Taoism.", a: "True", doc: "Taoism_Intro.pdf", pg: "5" },
    { id: "TF-7", type: "TF", topic: "Taoism", q: "The mind as a mirror is a metaphor embraced by Taoism only.", a: "False", doc: "Zhuangzi_Mirror.pdf", pg: "13" },
    { id: "TF-8", type: "TF", topic: "Taoism", q: "Zhuangzi's response at the death of his wife contradicts the spirit of the story of the fish partners in the drying lake.", a: "False", doc: "Zhuangzi_Stories.pdf", pg: "24" },
    { id: "TF-9", type: "TF", topic: "Taoism", q: "One branch of religious Taoism has practitioners who remain single, eat no meat and drink no alcohol.", a: "True", doc: "Religious_Taoism.pdf", pg: "6" },
    { id: "TF-10", type: "TF", topic: "Taoism", q: "One branch of religious Taoism has adopted the Buddhist heart sutra as part of their daily recitations too.", a: "True", doc: "Religious_Taoism.pdf", pg: "6" },
    { id: "TF-11", type: "TF", topic: "Taoism", q: "China's lunar rover Rabbit is so called because it moves about like a rabbit.", a: "False", doc: "Folklore.pdf", pg: "35" },
    { id: "TF-12", type: "TF", topic: "Confucianism", q: "Confucius was a contemporary of Laozi and was about 20 years his junior.", a: "True", doc: "Confucius_Intro.pdf", pg: "13" },
    { id: "TF-13", type: "TF", topic: "Confucianism", q: "Confucius praised his disciple Zi Gong, who rejected rewards for his financial assistance to free some captives.", a: "False", doc: "Confucius_Stories.pdf", pg: "56" },
    { id: "TF-14", type: "TF", topic: "Confucianism", q: "Mencius was born about 100 years after the death of Confucius, and was a contemporary of Zhuangzi.", a: "True", doc: "Mencius_Intro.pdf", pg: "2" },
    { id: "TF-15", type: "TF", topic: "Confucianism", q: "Confucianism is supportive of mercantilism.", a: "False", doc: "Confucius_Economics.pdf", pg: "10" },
    { id: "TF-16", type: "TF", topic: "Confucianism", q: "Confucius very efficiently held a hearing and gave his verdict on a lawsuit in which a father charged his son with filial impiety.", a: "False", doc: "Confucius_Legal.pdf", pg: "52" },
    { id: "TF-17", type: "TF", topic: "Legalism", q: "Mozi was the founder of Mohism and was not a Legalist nor Logician.", a: "False", doc: "Legalism_History.pdf", pg: "11" },
    { id: "TF-18", type: "TF", topic: "Legalism", q: "Rites and righteousness are upheld by Confucians only and not by Legalists.", a: "False", doc: "Legalism_GuanZhong.pdf", pg: "12" },
    { id: "TF-19", type: "TF", topic: "Legalism", q: "Fa also means administrative methods and standards, not just law or legal means.", a: "True", doc: "Legalism_Theory.pdf", pg: "13" },
    { id: "TF-20", type: "TF", topic: "Mohism", q: "Mozi was a military expert but called for peace.", a: "True", doc: "Mohism_Intro.pdf", pg: "6" },
    { id: "TF-21", type: "TF", topic: "Mohism", q: "Mozi was not good at the study of logic.", a: "False", doc: "Mohism_Logic.pdf", pg: "8" },
    { id: "TF-22", type: "TF", topic: "Mohism", q: "Mozi was in favor of the view that modern life should be patterned on the ways of the ancient sages.", a: "False", doc: "Mohism_Innovation.pdf", pg: "18" },
    { id: "TF-23", type: "TF", topic: "Mohism", q: "Mozi did not emphasize the importance of introspection, self-reflection and authenticity.", a: "False", doc: "Mohism_Ethics.pdf", pg: "16" },
    { id: "TF-24", type: "TF", topic: "Nominalism", q: "'The arrow flies fast, but there are times when it neither advances nor rests.' This statement comes from the book Zhuangzi.", a: "True", doc: "Nominalism_Zeno.pdf", pg: "59" },
    { id: "TF-25", type: "TF", topic: "Nominalism", q: "Hui Shi was wrong in assuming that the center of the world can be north of Yan and south of Yue.", a: "False", doc: "HuiShi_Paradox.pdf", pg: "29" },
    { id: "TF-26", type: "TF", topic: "Nominalism", q: "Nominalism in Chinese is called Mingjia.", a: "True", doc: "Nominalism_Intro.pdf", pg: "1" },
    { id: "TF-27", type: "TF", topic: "Strategy", q: "Sunzi was a contemporary of Confucius.", a: "True", doc: "Sunzi_History.pdf", pg: "2" },
    { id: "TF-28", type: "TF", topic: "Strategy", q: "Sunzi lived in the Warring States period.", a: "False", doc: "Sunzi_History.pdf", pg: "2" },
    { id: "TF-29", type: "TF", topic: "Strategy", q: "'The Art of War' is only applied to military affairs today.", a: "False", doc: "Sunzi_Intro.pdf", pg: "5" },
    { id: "TF-30", type: "TF", topic: "Buddhism", q: "Enlightenment in Buddhism cannot be fully expressed by language, because they believe language is only a limited tool of description.", a: "True", doc: "Zen_Philosophy.pdf", pg: "35" },
    { id: "TF-31", type: "TF", topic: "Buddhism", q: "In Zen, the mind is compared to a mirror as well.", a: "True", doc: "Zen_Huineng.pdf", pg: "46" },
    { id: "TF-32", type: "TF", topic: "Buddhism", q: "All Buddhist monks in China are vegetarians.", a: "False", doc: "Buddhism_Intro.pdf", pg: "17" },
    { id: "TF-33", type: "TF", topic: "Buddhism", q: "Buddhism believes that everyone can be a Buddha, just like everyone has the potential of becoming a professor.", a: "True", doc: "Buddhism_Terms.pdf", pg: "21" },
    { id: "TF-34", type: "TF", topic: "Buddhism", q: "One of the Buddhas, namely Amitabha, is so popular that his name is often used for greetings, exclamations, etc.", a: "True", doc: "PureLand.pdf", pg: "57" },
    { id: "TF-35", type: "TF", topic: "Neo-Confucianism", q: "Lu Jiuyuan was not a contemporary of Zhu Xi.", a: "False", doc: "NeoConf_History.pdf", pg: "2" },
    { id: "TF-36", type: "TF", topic: "Neo-Confucianism", q: "Zhu Xi in his poem also made an analogy between the mind and the mirror.", a: "True", doc: "ZhuXi_Heart.pdf", pg: "43" },
    { id: "TF-37", type: "TF", topic: "Neo-Confucianism", q: "Neo-Confucians warmly embrace Buddhism and Taoism and become strict religious practitioners too.", a: "False", doc: "NeoConf_Summary.pdf", pg: "26" },

    // --- MULTIPLE CHOICE QUESTIONS (1-113) ---
    // Yijing (1-15)
    { id: "MC-1", type: "MC", topic: "Yijing", q: "What is the Book of Changes called in Chinese?", o: ["Xin Jing", "Yi Jing", "Dao De Jing"], a: "Yi Jing", doc: "Yijing_Intro.pdf", pg: "13" },
    { id: "MC-2", type: "MC", topic: "Yijing", q: "How to say the eight trigrams that go around the Double-Fish Logo in Chinese?", o: ["ba gua (八卦)", "yin yang (阴阳)", "tai ji (太极)"], a: "ba gua (八卦)", doc: "Yijing_Theory.pdf", pg: "34" },
    { id: "MC-3", type: "MC", topic: "Yijing", q: "Who is the famous commentator of the Book of Changes?", o: ["Zhou Wenwang", "Fu Xi", "Kong Zi"], a: "Kong Zi", doc: "Yijing_History.pdf", pg: "20" },
    { id: "MC-4", type: "MC", topic: "Yijing", q: "The Positive (or Yang) can be represented by _____.", o: ["—", "•", "- -"], a: "—", doc: "Yijing_Theory.pdf", pg: "26" },
    { id: "MC-5", type: "MC", topic: "Yijing", q: "Such blocks as ☰, ☱, ☲, ☳, ☴, ☵, ☶, ☷ are called _____.", o: ["hexagrams", "trigrams", "hologram"], a: "trigrams", doc: "Yijing_Theory.pdf", pg: "65" },
    { id: "MC-6", type: "MC", topic: "Yijing", q: "The singularity point is NOT related to _____.", o: ["the big bang theory", "the black hole", "telepathy"], a: "telepathy", doc: "Yijing_Modern.pdf", pg: "20" },
    { id: "MC-7", type: "MC", topic: "Yijing", q: "\"Spooky action at a distance\" is a quotation from:", o: ["Einstein", "Bohr", "Laozi"], a: "Einstein", doc: "Yijing_Modern.pdf", pg: "44" },
    { id: "MC-8", type: "MC", topic: "Yijing", q: "The Danish quantum physicist Bohr liked the idea of Yin-Yang symbol for his coat of arms, on which the motto reads:", o: ["\"I think, therefore I am.\"", "\"Opposites are complementary.\"", "\"Go and have tea.\""], a: "\"Opposites are complementary.\"", doc: "Yijing_Modern.pdf", pg: "34" },
    { id: "MC-9", type: "MC", topic: "Yijing", q: "Quantum entanglement bears similarity to many of the following aspects of the Yin-Yang relationship EXCEPT:", o: ["non-duality", "moving in opposite directions", "constant mutual transformation"], a: "constant mutual transformation", doc: "Yijing_Modern.pdf", pg: "43" },
    { id: "MC-10", type: "MC", topic: "Yijing", q: "The concept of singularity point is very similar to which of the following concepts of Yijing?", o: ["tài jí (太极)", "wú jí (无极)", "bā guà (八卦)"], a: "tài jí (太极)", doc: "Yijing_Modern.pdf", pg: "50" },
    { id: "MC-11", type: "MC", topic: "Yijing", q: "The concept of black hole, or voidness, bears much resemblance to which of the following concepts of Yijing?", o: ["liǎng yí (两仪)", "wú jí (无极)", "tài jí (太极)"], a: "wú jí (无极)", doc: "Yijing_Modern.pdf", pg: "50" },
    { id: "MC-12", type: "MC", topic: "Yijing", q: "The best way to call the logo of double-fish with eight trigrams around it is:", o: ["tài jí tú (太极图)", "bā guà tú (卦图)", "tài jí bā guà tú (太极八卦图)"], a: "tài jí bā guà tú (太极八卦图)", doc: "Yijing_Theory.pdf", pg: "51" },
    { id: "MC-13", type: "MC", topic: "Yijing", q: "What is the theory that postulates that this 3-dimensional physical world may be just a projection of information from a 2-dimensional plane?", o: ["the hologram hypothesis", "the butterfly dream", "the manifested body"], a: "the hologram hypothesis", doc: "Yijing_Modern.pdf", pg: "53" },
    { id: "MC-14", type: "MC", topic: "Yijing", q: "All the audio and visual effects in computers are combinations of 0 and 1. In Yijing, these are NOT called:", o: ["yīn yáng (阴阳)", "wú jí (无极)", "liǎng yí (两仪)"], a: "wú jí (无极)", doc: "Yijing_Modern.pdf", pg: "55" },
    { id: "MC-15", type: "MC", topic: "Yijing", q: "Something positive is often accompanied by something negative. This way of looking at things is called:", o: ["sophistry", "ontology", "dialectics"], a: "dialectics", doc: "Yijing_Philosophy.pdf", pg: "61" },

    // Taoism (16-37)
    { id: "MC-16", type: "MC", topic: "Taoism", q: "The founder of philosophical Taoism is:", o: ["Laozi", "Zhuangzi", "Mencius"], a: "Laozi", doc: "Taoism_Laozi.pdf", pg: "1" },
    { id: "MC-17", type: "MC", topic: "Taoism", q: "What is the Chinese for 'The Way and Virtue', the earliest work of philosophical Taoism?", o: ["Xīn Jīng (心经)", "Dào Dé Jīng (道德经)", "Jīn Gāng Jīng (金刚经)"], a: "Dào Dé Jīng (道德经)", doc: "Laozi_Daodejing.pdf", pg: "11" },
    { id: "MC-18", type: "MC", topic: "Taoism", q: "The Taoist concept of inaction, or effortless action, in Chinese is called:", o: ["zì rán (自然)", "wú zhēng (无争)", "wú wéi (无为)"], a: "wú wéi (无为)", doc: "Taoism_Intro.pdf", pg: "5" },
    { id: "MC-19", type: "MC", topic: "Taoism", q: "Which historical period did Laozi live in?", o: ["Chūn Qiū (春秋)", "Zhàn Guó (战国)", "Sòng Míng (宋明)"], a: "Chūn Qiū (春秋)", doc: "Laozi_History.pdf", pg: "13" },
    { id: "MC-20", type: "MC", topic: "Taoism", q: "The author of Daodejing lived in a period of about how many years ago?", o: ["about 2300 years ago", "about 2500 years ago", "about 2000 years ago"], a: "about 2500 years ago", doc: "Laozi_History.pdf", pg: "20" },
    { id: "MC-21", type: "MC", topic: "Taoism", q: "The story of the old man who lost his horse in the border region tells us that:", o: ["law is pivotal", "white horses are not horses", "positive and negative things often go hand in hand"], a: "positive and negative things often go hand in hand", doc: "Taoism_Stories.pdf", pg: "21" },
    { id: "MC-22", type: "MC", topic: "Taoism", q: "Laozi is said to have opened his mouth showing all his teeth gone while his tongue remaining. This describes:", o: ["shàng shàn ruò shuǐ (上善若水)", "zhī zú cháng lè (知足常乐)", "huò fú xiāng yī (祸福相依)"], a: "shàng shàn ruò shuǐ (上善若水)", doc: "Taoism_Ethics.pdf", pg: "22" },
    { id: "MC-23", type: "MC", topic: "Taoism", q: "Which of the following is NOT a Taoist resort?", o: ["Qīng Chéng Shān", "É Méi Shān", "Qīng Yáng Gōng"], a: "É Méi Shān", doc: "Taoism_Intro.pdf", pg: "2" },
    { id: "MC-24", type: "MC", topic: "Taoism", q: "The second most important philosophical Taoist master is:", o: ["Gongsun Long", "Mo Zi", "Zhuangzi"], a: "Zhuangzi", doc: "Zhuangzi_Intro.pdf", pg: "1" },
    { id: "MC-25", type: "MC", topic: "Taoism", q: "The collection of works by Zhuangzi is called:", o: ["Zhuangzi", "Da Xue", "Zhong Yong"], a: "Zhuangzi", doc: "Zhuangzi_Intro.pdf", pg: "3" },
    { id: "MC-26", type: "MC", topic: "Taoism", q: "Zhuangzi is NOT famous for:", o: ["pursuing transcendence", "applying the art of war", "using allegorical stories"], a: "applying the art of war", doc: "Zhuangzi_Intro.pdf", pg: "5" },
    { id: "MC-27", type: "MC", topic: "Taoism", q: "Zhuangzi had a dream in which he became a butterfly. This story is NOT related to:", o: ["relativity of time", "transformation of things", "the importance of sweet innocence"], a: "the importance of sweet innocence", doc: "Zhuangzi_Stories.pdf", pg: "9" },
    { id: "MC-28", type: "MC", topic: "Taoism", q: "The story of the happiness of fish is related to:", o: ["insight into logic", "detachment from desire", "unity with nature"], a: "insight into logic", doc: "Zhuangzi_Stories.pdf", pg: "11" },
    { id: "MC-29", type: "MC", topic: "Taoism", q: "\"The Perfect Man uses his mind like a mirror.\" This is NOT related to:", o: ["naturalness", "frugality", "inaction"], a: "frugality", doc: "Zhuangzi_Mirror.pdf", pg: "13" },
    { id: "MC-30", type: "MC", topic: "Taoism", q: "The story of fighting at the snail's antennas indicates:", o: ["loyalty and bravery", "law and order", "men are short-sighted"], a: "men are short-sighted", doc: "Zhuangzi_Stories.pdf", pg: "21" },
    { id: "MC-31", type: "MC", topic: "Taoism", q: "The story of the fish partners in a drying lake is intended to tell us:", o: ["to detach from emotional bondage", "to help each other", "to protect the eco-system"], a: "to detach from emotional bondage", doc: "Zhuangzi_Stories.pdf", pg: "24" },
    { id: "MC-32", type: "MC", topic: "Taoism", q: "In religious Taoism, the ruler in heaven is called:", o: ["Yu Tu (玉兔)", "Yu Di (玉帝)", "Lao Zi (老子)"], a: "Yu Di (玉帝)", doc: "Religious_Taoism.pdf", pg: "32" },
    { id: "MC-33", type: "MC", topic: "Taoism", q: "Religious Taoism has two main branches, NOT including:", o: ["Zheng Yi Jiao", "Quan Zhen Jiao", "Da Cheng Jiao"], a: "Da Cheng Jiao", doc: "Religious_Taoism.pdf", pg: "6" },
    { id: "MC-34", type: "MC", topic: "Taoism", q: "Early Taoist alchemists were believed to have invented _____ by chance.", o: ["gunpowder", "compass", "paper-making"], a: "gunpowder", doc: "Taoism_History.pdf", pg: "34" },
    { id: "MC-35", type: "MC", topic: "Taoism", q: "According to Chinese folklore, the lady who flies to the moon with her rabbit is:", o: ["Nu Wa", "Chang'e", "Fu Hao"], a: "Chang'e", doc: "Folklore.pdf", pg: "35" },
    { id: "MC-36", type: "MC", topic: "Taoism", q: "The immortal or deity who is a symbol of longevity is called:", o: ["Fu Xing", "Lu Xing", "Shou Xing"], a: "Shou Xing", doc: "Folklore.pdf", pg: "36" },
    { id: "MC-37", type: "MC", topic: "Taoism", q: "Before the Spring Festival, Chinese people put up pictures of door guardians called:", o: ["Men Shen", "Tu Di Gong", "Zao Shen"], a: "Men Shen", doc: "Folklore.pdf", pg: "37" },

    // Confucianism (38-52)
    { id: "MC-38", type: "MC", topic: "Confucianism", q: "The contention between different philosophies in the Spring and Autumn period is called:", o: ["si shu wu jing", "bai jia zheng ming", "bai ma fei ma"], a: "bai jia zheng ming", doc: "Confucius_Intro.pdf", pg: "38" },
    { id: "MC-39", type: "MC", topic: "Confucianism", q: "Confucianism was established by:", o: ["Meng Zi", "Xun Zi", "Kong Zi"], a: "Kong Zi", doc: "Confucius_Intro.pdf", pg: "39" },
    { id: "MC-40", type: "MC", topic: "Confucianism", q: "The second most important Confucian master is:", o: ["Meng Zi", "Xun Zi", "Kong Zi"], a: "Meng Zi", doc: "Mencius_Intro.pdf", pg: "40" },
    { id: "MC-41", type: "MC", topic: "Confucianism", q: "Confucianism in Chinese is called:", o: ["Dao Jia", "Ru Jia", "Ming Jia"], a: "Ru Jia", doc: "Confucius_Intro.pdf", pg: "41" },
    { id: "MC-42", type: "MC", topic: "Confucianism", q: "Confucius was NOT fond of:", o: ["governance", "education", "non-competition"], a: "non-competition", doc: "Confucius_Ethics.pdf", pg: "42" },
    { id: "MC-43", type: "MC", topic: "Confucianism", q: "The core value of Confucianism is:", o: ["rén (仁)", "yì (义)", "lǐ (礼)"], a: "rén (仁)", doc: "Confucius_Ethics.pdf", pg: "43" },
    { id: "MC-44", type: "MC", topic: "Confucianism", q: "Filial piety in Chinese is called:", o: ["zhong", "xiao", "jie"], a: "xiao", doc: "Confucius_Ethics.pdf", pg: "44" },
    { id: "MC-45", type: "MC", topic: "Confucianism", q: "The Book of Rites, or the Book of Propriety, is called:", o: ["Shang Shu", "Shi Jing", "Zhou Li"], a: "Zhou Li", doc: "Confucius_Classics.pdf", pg: "45" },
    { id: "MC-46", type: "MC", topic: "Confucianism", q: "The words and deeds of Confucius were recorded in:", o: ["Lun Yu", "Tan Jing", "Chun Qiu"], a: "Lun Yu", doc: "Confucius_Classics.pdf", pg: "46" },
    { id: "MC-47", type: "MC", topic: "Confucianism", q: "The Confucian value \"Ren\" means:", o: ["righteousness", "humanity or humaneness", "loyalty"], a: "humanity or humaneness", doc: "Confucius_Ethics.pdf", pg: "47" },
    { id: "MC-48", type: "MC", topic: "Confucianism", q: "Mencius's mother moved their house _____ times for his education.", o: ["once", "2 times", "3 times"], a: "3 times", doc: "Mencius_Stories.pdf", pg: "48" },
    { id: "MC-49", type: "MC", topic: "Confucianism", q: "Little Mencius's mother cut the cloth on the loom into halves to demonstrate:", o: ["giving up study is loss", "poor quality", "making a coat"], a: "giving up study is loss", doc: "Mencius_Stories.pdf", pg: "49" },
    { id: "MC-50", type: "MC", topic: "Confucianism", q: "Mencius is of the view that:", o: ["nature is evil", "common people are most valuable", "ruler is significant"], a: "common people are most valuable", doc: "Mencius_Politics.pdf", pg: "50" },
    { id: "MC-51", type: "MC", topic: "Confucianism", q: "\"Believing in everything in books is worse than having no books\" is from:", o: ["Mozi", "Confucius", "Mencius"], a: "Mencius", doc: "Mencius_Education.pdf", pg: "51" },
    { id: "MC-52", type: "MC", topic: "Confucianism", q: "The Confucian ideal of a \"superior man\" or \"gentleman\" is called:", o: ["jun zi", "sheng ren", "yi shi"], a: "jun zi", doc: "Confucius_Ethics.pdf", pg: "52" },

    // Legalism (53-67)
    { id: "MC-53", type: "MC", topic: "Legalism", q: "Legalism advocates the rule of law. What is this branch called in Chinese?", o: ["Bing Jia", "Fa Jia", "Fo Jia"], a: "Fa Jia", doc: "Legalism_Intro.pdf", pg: "53" },
    { id: "MC-54", type: "MC", topic: "Legalism", q: "Fa is theoretically derived from which of the following works?", o: ["Shi Jing", "Shang Shu", "Zhou Li"], a: "Zhou Li", doc: "Legalism_Intro.pdf", pg: "10" },
    { id: "MC-55", type: "MC", topic: "Legalism", q: "Which of the following Legalists lived in the Spring and Autumn period?", o: ["Guan Zhong", "Shang Yang", "Han Fei Zi"], a: "Guan Zhong", doc: "Legalism_History.pdf", pg: "11" },
    { id: "MC-56", type: "MC", topic: "Legalism", q: "\"Only when the granary is full will people learn etiquette...\" is a quotation from:", o: ["Taoism", "Legalism", "Confucianism"], a: "Legalism", doc: "Legalism_GuanZhong.pdf", pg: "15" },
    { id: "MC-57", type: "MC", topic: "Legalism", q: "\"Rites, righteousness, integrity, sense of shame are the four dimensions...\" is from:", o: ["Confucianism", "Taoism", "Legalism"], a: "Legalism", doc: "Legalism_GuanZhong.pdf", pg: "16" },
    { id: "MC-58", type: "MC", topic: "Legalism", q: "Mozi mentions artisans using set squares and compasses as 'Models'. What does 'Model' mean here?", o: ["Fǎ (法)", "Dào (道)", "Rén (仁)"], a: "Fǎ (法)", doc: "Legalism_Theory.pdf", pg: "58" },
    { id: "MC-59", type: "MC", topic: "Legalism", q: "Who established credibility by rewarding people for moving a log?", o: ["Mo Zi", "Shang Yang", "Hui Shi"], a: "Shang Yang", doc: "Legalism_ShangYang.pdf", pg: "59" },
    { id: "MC-60", type: "MC", topic: "Legalism", q: "Who is the first real emperor of China whose reign was characterized by Legalism?", o: ["Tang Tai Zong", "Han Wu Di", "Qin Shi Huang"], a: "Qin Shi Huang", doc: "Legalism_Qin.pdf", pg: "60" },
    { id: "MC-61", type: "MC", topic: "Legalism", q: "Which book was written around 240 BC and thought as the greatest Legalist text?", o: ["Han Feizi", "Guanzi", "Mengzi"], a: "Han Feizi", doc: "Legalism_HanFei.pdf", pg: "61" },
    { id: "MC-62", type: "MC", topic: "Legalism", q: "Han Fei's prince must surround himself with an aura of _____.", o: ["amicability", "majesty and power", "benevolence"], a: "majesty and power", doc: "Legalism_Theory.pdf", pg: "62" },
    { id: "MC-63", type: "MC", topic: "Legalism", q: "The story of the seller with all-penetrating spear and impenetrable shield is from:", o: ["Mozi", "Lunyu", "Han Feizi"], a: "Han Feizi", doc: "Legalism_HanFei.pdf", pg: "63" },
    { id: "MC-64", type: "MC", topic: "Legalism", q: "Which school tends to grant authority to \"wise and virtuous ministers\"?", o: ["Confucianism", "Legalism", "Nominalism"], a: "Confucianism", doc: "Legalism_Vs_Conf.pdf", pg: "64" },
    { id: "MC-65", type: "MC", topic: "Legalism", q: "The selfish view of human nature is a pillar of the _____.", o: ["Taoists", "Legalists", "Confucians"], a: "Legalists", doc: "Legalism_Theory.pdf", pg: "65" },
    { id: "MC-66", type: "MC", topic: "Legalism", q: "Legalists try to replace aristocracy with _____.", o: ["authority", "benevolence", "bureaucracy"], a: "bureaucracy", doc: "Legalism_Summary.pdf", pg: "66" },
    { id: "MC-67", type: "MC", topic: "Legalism", q: "Legalists do NOT advocate _____.", o: ["fostering charisma", "central government", "food production"], a: "fostering charisma", doc: "Legalism_Summary.pdf", pg: "67" },

    // Mohism (68-75)
    { id: "MC-68", type: "MC", topic: "Mohism", q: "In 2016, China launched a quantum satellite named _____ in homage to his writings on optics.", o: ["Pan Jianwei", "Mozi", "Han Feizi"], a: "Mozi", doc: "Mohism_Science.pdf", pg: "68" },
    { id: "MC-69", type: "MC", topic: "Mohism", q: "Which pair are NOT natives of Shandong province?", o: ["Confucius and Mencius", "Sunzi and Mozi", "Laozi and Zhuangzi"], a: "Laozi and Zhuangzi", doc: "Mohism_History.pdf", pg: "69" },
    { id: "MC-70", type: "MC", topic: "Mohism", q: "Who viewed elaborate celebrations and funerals as detrimental to common people?", o: ["Mò Zǐ", "Sūn Zǐ", "Mèng Zǐ"], a: "Mò Zǐ", doc: "Mohism_Ethics.pdf", pg: "70" },
    { id: "MC-71", type: "MC", topic: "Mohism", q: "Who taught that everyone is equal in the eyes of heaven?", o: ["Mèng Zǐ", "Mò Zǐ", "Sūn Zǐ"], a: "Mò Zǐ", doc: "Mohism_Ethics.pdf", pg: "71" },
    { id: "MC-72", type: "MC", topic: "Mohism", q: "Mozi's idea of \"universal love\" is called _____ in Chinese.", o: ["jie yong", "fei gong", "jian ai"], a: "jian ai", doc: "Mohism_Ethics.pdf", pg: "72" },
    { id: "MC-73", type: "MC", topic: "Mohism", q: "Mozi was sad at dyeing silk because _____.", o: ["costly", "silk better-looking", "reminded of sad past"], a: "reminded of sad past", doc: "Mohism_Ethics.pdf", pg: "73" },
    { id: "MC-74", type: "MC", topic: "Mohism", q: "\"When one throws to me a peach, I return to him a plum\" means _____.", o: ["tooth for tooth", "favor for favor", "mismatch"], a: "favor for favor", doc: "Mohism_Ethics.pdf", pg: "74" },
    { id: "MC-75", type: "MC", topic: "Mohism", q: "Which is NOT a contribution by Mozi?", o: ["lever principle", "light travels straight", "general relativity"], a: "general relativity", doc: "Mohism_Science.pdf", pg: "75" },

    // Nominalism (76-85)
    { id: "MC-76", type: "MC", topic: "Nominalism", q: "Followers of Nominalism are NOT called _____.", o: ["Rationalists", "Logicians", "Disputers"], a: "Rationalists", doc: "Nominalism_Intro.pdf", pg: "76" },
    { id: "MC-77", type: "MC", topic: "Nominalism", q: "Nominalism grew out of _____.", o: ["Neo-Confucianism", "Mohism", "The Book of Rites"], a: "Mohism", doc: "Nominalism_Intro.pdf", pg: "77" },
    { id: "MC-78", type: "MC", topic: "Nominalism", q: "Hui Shi and Gongsun Long lived in the _____ period.", o: ["Western Zhou", "Spring/Autumn", "Warring States"], a: "Warring States", doc: "Nominalism_History.pdf", pg: "78" },
    { id: "MC-79", type: "MC", topic: "Nominalism", q: "Hui Shi's philosophy relies on classic texts, most frequently _____.", o: ["Zhuāngzǐ", "Hán Fēizǐ", "Lüshì Chūnqiū"], a: "Zhuāngzǐ", doc: "Nominalism_History.pdf", pg: "79" },
    { id: "MC-80", type: "MC", topic: "Nominalism", q: "\"I set off for Yue today and came there yesterday\" suggests _____.", o: ["absurdity", "relativity of time and space", "devotion"], a: "relativity of time and space", doc: "HuiShi_Paradox.pdf", pg: "80" },
    { id: "MC-81", type: "MC", topic: "Nominalism", q: "Hui Shi is remembered as the proponent of _____.", o: ["mind as mirror", "separating hardness", "harmonizing sameness and difference"], a: "harmonizing sameness and difference", doc: "HuiShi_Theory.pdf", pg: "81" },
    { id: "MC-82", type: "MC", topic: "Nominalism", q: "\"Heaven is as low as earth; mountains and lakes are level\" attempts to _____.", o: ["harmonize sameness and difference", "compare mind to mirror", "divide hardness"], a: "harmonize sameness and difference", doc: "HuiShi_Theory.pdf", pg: "82" },
    { id: "MC-83", type: "MC", topic: "Nominalism", q: "\"The happiness of fish\" debate was between Zhuangzi and _____.", o: ["Gongsun Long", "Hui Shi", "Yin Wen"], a: "Hui Shi", doc: "HuiShi_Theory.pdf", pg: "83" },
    { id: "MC-84", type: "MC", topic: "Nominalism", q: "Which statement is NOT attributed to Gongsun Long?", o: ["White horses are not horses", "Hardness and whiteness different", "Linked rings can be separated"], a: "Linked rings can be separated", doc: "GongsunLong.pdf", pg: "84" },
    { id: "MC-85", type: "MC", topic: "Nominalism", q: "Which one of the following is NOT a Greek paradox?", o: ["flying bird shadow", "tortoise race", "flying arrow static"], a: "flying bird shadow", doc: "Nominalism_Zeno.pdf", pg: "85" },

    // Strategy (86-89)
    { id: "MC-86", type: "MC", topic: "Strategy", q: "The Art of War was written by:", o: ["Mozi", "Sunzi", "Zhu Xi"], a: "Sunzi", doc: "Sunzi_Intro.pdf", pg: "86" },
    { id: "MC-87", type: "MC", topic: "Strategy", q: "Who is NOT a contemporary of Sunzi?", o: ["Laozi", "Confucius", "Gongsun Long"], a: "Gongsun Long", doc: "Sunzi_History.pdf", pg: "87" },
    { id: "MC-88", type: "MC", topic: "Strategy", q: "The highest art of war is _____.", o: ["rivalry of strategies", "diplomatic mediation", "direct fight"], a: "rivalry of strategies", doc: "Sunzi_Theory.pdf", pg: "88" },
    { id: "MC-89", type: "MC", topic: "Strategy", q: "\"If you know your enemy and know yourself...\" in Chinese is:", o: ["bu zhan er qu", "zhi bi zhi ji", "shang bing fa mou"], a: "zhi bi zhi ji", doc: "Sunzi_Theory.pdf", pg: "89" },

    // Buddhism (90-101)
    { id: "MC-90", type: "MC", topic: "Buddhism", q: "Which one is NOT a Buddhist mountain?", o: ["É Méi Shān", "Lè Shān", "Qīng Chéng Shān"], a: "Qīng Chéng Shān", doc: "Buddhism_Intro.pdf", pg: "90" },
    { id: "MC-91", type: "MC", topic: "Buddhism", q: "\"All that we are is result of our thoughts\" is characteristic of:", o: ["Fó Jiào", "Dào Jiào", "Rú Jiào"], a: "Fó Jiào", doc: "Buddhism_Sutras.pdf", pg: "91" },
    { id: "MC-92", type: "MC", topic: "Buddhism", q: "In Buddhism, the highest heaven or realm is _____.", o: ["physical forms", "formless realm", "desire"], a: "formless realm", doc: "Buddhism_Terms.pdf", pg: "92" },
    { id: "MC-93", type: "MC", topic: "Buddhism", q: "The shortest Buddhist scripture in Chinese (about 260 chars) is:", o: ["Platform Sutra", "Diamond Sutra", "Heart Sutra"], a: "Heart Sutra", doc: "Buddhism_Sutras.pdf", pg: "93" },
    { id: "MC-94", type: "MC", topic: "Buddhism", q: "The term \"dharma body\" means:", o: ["formless/all-pervasive", "manifested body", "reincarnated body"], a: "formless/all-pervasive", doc: "Buddhism_Trinity.pdf", pg: "94" },
    { id: "MC-95", type: "MC", topic: "Buddhism", q: "Which one of the following is NOT a feature of Zen?", o: ["Hit with stick", "Recite Amitabha", "Tell inquirer have tea"], a: "Recite Amitabha", doc: "Zen_Philosophy.pdf", pg: "95" },
    { id: "MC-96", type: "MC", topic: "Buddhism", q: "Generally, Han and Tibetan tradition Buddhism are called:", o: ["Hinayana", "Theravada", "Mahayana"], a: "Mahayana", doc: "Buddhism_Schools.pdf", pg: "96" },
    { id: "MC-97", type: "MC", topic: "Buddhism", q: "Theravada is mainly practiced in:", o: ["Yunnan province", "Inner Mongolia", "Guangxi"], a: "Yunnan province", doc: "Buddhism_Schools.pdf", pg: "97" },
    { id: "MC-98", type: "MC", topic: "Buddhism", q: "Which is NOT one of the most influential Han Buddhism sects?", o: ["the Zen sect", "the Dharma-Image", "the Pure Land sect"], a: "the Dharma-Image", doc: "Buddhism_Han.pdf", pg: "98" },
    { id: "MC-99", type: "MC", topic: "Buddhism", q: "Which sect is the latest one in Tibetan Buddhism?", o: ["the Red sect", "the White sect", "the Yellow sect"], a: "the Yellow sect", doc: "Buddhism_Tibetan.pdf", pg: "99" },
    { id: "MC-100", type: "MC", topic: "Buddhism", q: "\"Form does not differ from emptiness...\" verses are from:", o: ["Heart Sutra", "Diamond Sutra", "Platform Sutra"], a: "Heart Sutra", doc: "Buddhism_Sutras.pdf", pg: "100" },
    { id: "MC-101", type: "MC", topic: "Buddhism", q: "Bodhisattva Avalokiteshvara is called _____ in China.", o: ["Wén Shū", "Guān Yīn", "Shì Jiā"], a: "Guān Yīn", doc: "Buddhism_PureLand.pdf", pg: "101" },

    // Neo-Confucianism (102-113)
    { id: "MC-102", type: "MC", topic: "Neo-Confucianism", q: "Neo-Confucianism arose and prospered in following dynasties EXCEPT:", o: ["Song", "Ming", "Tang"], a: "Tang", doc: "NeoConf_History.pdf", pg: "102" },
    { id: "MC-103", type: "MC", topic: "Neo-Confucianism", q: "Neo-Confucianism has two main branches. Which is NOT one of them?", o: ["the Esoteric school", "Cheng-Zhu Rationalism", "Lu-Wang Mind school"], a: "the Esoteric school", doc: "NeoConf_Intro.pdf", pg: "103" },
    { id: "MC-104", type: "MC", topic: "Neo-Confucianism", q: "The birth of Neo-Confucianism is about _____ years ago.", o: ["1500", "1000", "2000"], a: "1000", doc: "NeoConf_History.pdf", pg: "104" },
    { id: "MC-105", type: "MC", topic: "Neo-Confucianism", q: "The 'master of masters' in the lineage is _____.", o: ["Zhū Xī", "Chéng Hào", "Zhōu Dūnyí"], a: "Zhōu Dūnyí", doc: "NeoConf_History.pdf", pg: "105" },
    { id: "MC-106", type: "MC", topic: "Neo-Confucianism", q: "Who is the most influential Neo-Confucian master (annotations for 600 years)?", o: ["Zhū Xī", "Chéng Yí", "Chéng Hào"], a: "Zhū Xī", doc: "NeoConf_History.pdf", pg: "106" },
    { id: "MC-107", type: "MC", topic: "Neo-Confucianism", q: "Which part of theory is NOT favored by Neo-Confucianism?", o: ["Taoism", "Legalism", "Buddhism"], a: "Legalism", doc: "NeoConf_Summary.pdf", pg: "107" },
    { id: "MC-108", type: "MC", topic: "Neo-Confucianism", q: "The objective to become a \"sage\" is called _____ in Chinese.", o: ["Zhēn Rén", "Xián Rén", "Shèng Rén"], a: "Shèng Rén", doc: "NeoConf_Philosophy.pdf", pg: "108" },
    { id: "MC-109", type: "MC", topic: "Neo-Confucianism", q: "Neo-Confucians maintain that everyone has perfect _____.", o: ["Lǐ (Principle)", "Lǐ (Rites)", "Rén"], a: "Lǐ (Principle)", doc: "NeoConf_Philosophy.pdf", pg: "109" },
    { id: "MC-110", type: "MC", topic: "Neo-Confucianism", q: "Which statement is NOT originated from Neo-Confucianism?", o: ["Zhī Xíng Hé Yī", "Sè Jí Shì Kōng", "Lǐ Zài Qì Xiān"], a: "Sè Jí Shì Kōng", doc: "NeoConf_Summary.pdf", pg: "110" },
    { id: "MC-111", type: "MC", topic: "Neo-Confucianism", q: "\"The universe is my mind, and my mind is the universe\" is from:", o: ["Gōngsūn Lóng", "Wáng Yángmíng", "Lù Jiǔyuān"], a: "Lù Jiǔyuān", doc: "NeoConf_History.pdf", pg: "111" },
    { id: "MC-112", type: "MC", topic: "Neo-Confucianism", q: "\"I think, therefore the flower exists\" describes which personage?", o: ["Wáng Yángmíng", "Chéng Hào", "Zhū Xī"], a: "Wáng Yángmíng", doc: "NeoConf_WangYangming.pdf", pg: "112" },
    { id: "MC-113", type: "MC", topic: "Neo-Confucianism", q: "Which one of the following is NOT related to Wang Yangming?", o: ["Four-Line Axiom", "Bodhi originally no tree poem", "Longchang Awakening"], a: "Bodhi originally no tree poem", doc: "NeoConf_WangYangming.pdf", pg: "113" }
];
